### PR TITLE
Add support for AsyncAPI 2.0.0

### PR DESCRIPTION
**Pull request by fmvilas**
Hey Mike!

This PR adds support for AsyncAPI 2.0.0 and removes support for AsyncAPI 1.x.

We're not supporting 1.x versions anymore but I'd understand if you don't want to remove support here. Up to you :)

PS: I don't know how to test this PR. If you could do it I'd be eternally grateful 😄

### CODE REVIEW

**Comment by Sacro** [comment]
@MikeRalphson any chance of getting this merged please?

**Comment by MikeRalphson** [comment]
Yep, just want to re-add support for AsyncApi v1 if you use a filename like `asyncapi1.yaml`

**Comment by MikeRalphson** [comment]
Thanks @fmvilas !

**Comment by fmvilas** [comment]
Thank you, Mike!

**Comment by MikeRalphson** [comment]
Will be releasing the new version in a few minutes, will ping on Slack.

**Comment by MikeRalphson** [comment]
Did you use one of the command palette commands? What is the name of your input file?

**Comment by Sacro** [comment]
Please move this to another ticket

**Comment by WaleedAshraf** [comment]
moved here: https://github.com/Mermade/openapi-lint-vscode/issues/19

**Pull request merged**
